org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
## Environment Properties
minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=parchment
mapping_version=2022.03.06-1.16.5
curseforge_id=1264512
modrinth_id=CV3BPuYF
## Mod Properties
mod_id=paginatedadvancements
mod_name=ForgedPaginatedAdvancements
mod_license=MIT
mod_version=0.0.1+1.16.5
mod_group_id=cn.sh1rocu
mod_authors=Sh1roCu
mod_description=PaginatedAdvancements unofficial (Neo)Forge port
## Dependence
cloth_config_version=4.16.91
